const bookData = [
  {
    id: 1,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    publisher: 'Scribner',
    year: 1925,
    pages: 180,
    image:
      'https://images-na.ssl-images-amazon.com/images/I/51TCVvPnU6L._SX323_BO1,204,203,200_.jpg',
  },
  {
    id: 2,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    publisher: 'J. B. Lippincott & Co.',
    year: 1960,
    pages: 281,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81jzLlsqt1L.jpg',
  },
  {
    id: 3,
    title: '1984',
    author: 'George Orwell',
    publisher: 'Secker & Warburg',
    year: 1949,
    pages: 328,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81ZV8e8PXrL.jpg',
  },
  {
    id: 4,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publisher: 'T. Egerton, Whitehall',
    year: 1813,
    pages: 279,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81Uw5sYUQNL.jpg',
  },
  {
    id: 5,
    title: 'The Catcher in the Rye',
    author: 'J. D. Salinger',
    publisher: 'Little, Brown and Company',
    year: 1951,
    pages: 277,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81bIM+8da9L.jpg',
  },
  {
    id: 6,
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    publisher: 'Bloomsbury',
    year: 1997,
    pages: 223,
    image: 'https://images-na.ssl-images-amazon.com/images/I/91Nhwytoj6L.jpg',
  },
  {
    id: 7,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    publisher: 'George Allen & Unwin',
    year: 1937,
    pages: 310,
    image: 'https://images-na.ssl-images-amazon.com/images/I/91Pc7LNqdJL.jpg',
  },
  {
    id: 8,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    publisher: 'George Allen & Unwin',
    year: 1954,
    pages: 423,
    image: 'https://images-na.ssl-images-amazon.com/images/I/91nWu19v3kL.jpg',
  },
  {
    id: 9,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    publisher: 'Richard Bentley (UK), Harper & Brothers (US)',
    year: 1851,
    pages: 585,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81Ji1rZSaZL.jpg',
  },
  {
    id: 10,
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    publisher: 'Macmillan',
    year: 1865,
    pages: 192,
    image: 'https://images-na.ssl-images-amazon.com/images/I/81ZvphgjJfL.jpg',
  },
];

export default bookData;
